In [8]:
import pandas as pd
from sqlalchemy import create_engine, text

In [9]:
# Definition des paramètres de connexion à la base de données
db_username = 'postgres'
db_password = 'pass123'
db_host = '127.0.0.1'
db_port = '5432'
db_name = 'postgres'

In [10]:
# Création du moteur SQLAlchemy
engine = create_engine(f'postgresql+psycopg2://{db_username}:{db_password}@{db_host}:{db_port}/{db_name}')

In [11]:
# Exécution d'une requête simple
sql_query = "SELECT * FROM ville"
df_villes = pd.read_sql(sql_query, engine)
df_villes

,ville_id,ville_departement,ville_slug,ville_nom,ville_nom_simple,ville_nom_reel,ville_nom_soundex,ville_nom_metaphone,ville_code_postal,ville_commune,...,ville_densite_2010,ville_surface,ville_longitude_deg,ville_latitude_deg,ville_longitude_grd,ville_latitude_grd,ville_longitude_dms,ville_latitude_dms,ville_zmin,ville_zmax
0,1,01,ozan,OZAN,ozan,Ozan,O250,OSN,01190,284,...,93,6.60,4.91667,46.38330,2866,51546,+45456,462330,170.0,205.0
1,2,01,cormoranche-sur-saone,CORMORANCHE-SUR-SAONE,cormoranche sur saone,Cormoranche-sur-SaÃ´ne,C65652625,KRMRNXSRSN,01290,123,...,107,9.85,4.83333,46.23330,2772,51379,+44953,461427,168.0,211.0
2,3,01,plagne-01,PLAGNE,plagne,Plagne,P425,PLKN,01130,298,...,20,6.20,5.73333,46.18330,3769,51324,+54342,461131,560.0,922.0
3,4,01,tossiat,TOSSIAT,tossiat,Tossiat,T230,TST,01250,422,...,138,10.17,5.31667,46.13330,3309,51268,+51854,460828,244.0,501.0
4,5,01,pouillat,POUILLAT,pouillat,Pouillat,P430,PLT,01250,309,...,14,6.23,5.43333,46.33330,3435,51475,+52542,461938,333.0,770.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36695,36825,976,sada,SADA,sada,Sada,S300,ST,97640,616,...,933,10.92,45.10470,-12.84860,None,None,None,None,NaN,NaN
36696,36826,976,tsingoni,TSINGONI,tsingoni,Tsingoni,T2525,TSNKN,97680,617,...,300,34.76,45.10700,-12.78970,None,None,None,None,NaN,NaN
36697,36827,971,st-barthelemy,SAINT BARTHELEMY,st barthelemy,Saint-BarthÃ©lemy,S5316345,SNTPR0LM,97133,123,...,372,24.00,-62.83330,17.91670,None,None,None,None,NaN,NaN
36698,36828,971,st-martin,SAINT MARTIN,st martin,Saint-Martin,S535635,SNTMRTN,97150,127,...,695,53.20,18.09130,-63.08290,None,None,None,None,NaN,NaN
36699,36830,975,st-pierre-et-miquelon,SAINT PIERRE ET MIQUELON,st pierre et miquelon,Saint-Pierre-et-Miquelon,S531635245,SNTPR,97500,501,...,25,242.00,46.71070,1.71819,None,None,None,None,NaN,NaN

In [12]:
# Exécution d'une requête paramètrée
departement_a_rechercher = "60"

sql_query = text("SELECT * FROM public.ville WHERE ville_departement = :departement_code")
params = {"departement_code": departement_a_rechercher}
df_villes_departement = pd.read_sql_query(sql_query, engine, params=params)
df_villes_departement

,ville_id,ville_departement,ville_slug,ville_nom,ville_nom_simple,ville_nom_reel,ville_nom_soundex,ville_nom_metaphone,ville_code_postal,ville_commune,...,ville_densite_2010,ville_surface,ville_longitude_deg,ville_latitude_deg,ville_longitude_grd,ville_latitude_grd,ville_longitude_dms,ville_latitude_dms,ville_zmin,ville_zmax
0,23339,60,berneuil-en-bray,BERNEUIL-EN-BRAY,berneuil en bray,Berneuil-en-Bray,B654516,BRNLNBR,60390,063,...,52,15.15,2.06667,49.3500,-301,54832,+20357,492056,88,224
1,23340,60,biermont,BIERMONT,biermont,Biermont,B653,BRMNT,60490,071,...,43,3.92,2.73333,49.5833,441,55091,+24402,493454,63,92
2,23341,60,abbeville-saint-lucien,ABBEVILLE-SAINT-LUCIEN,abbeville saint lucien,Abbeville-Saint-Lucien,A14253425,ABFLSNTLSN,60480,003,...,100,5.26,2.16667,49.5167,-185,55019,+21011,493101,130,156
3,23342,60,sainte-eusoye,SAINTE-EUSOYE,sainte eusoye,Sainte-Eusoye,S532,SNTSY,60480,573,...,32,8.48,2.23333,49.5833,-101,55086,+21443,493437,95,178
4,23343,60,morienval,MORIENVAL,morienval,Morienval,M6514,MRNFL,60127,430,...,39,25.74,2.93333,49.3000,648,54776,+25512,491753,52,171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
688,24027,60,clermont-60,CLERMONT,clermont,Clermont,C4653,KLRMNT,60600,157,...,1819,5.81,2.40000,49.3833,84,54866,+22445,492244,48,162
689,24028,60,milly-sur-therain,MILLY-SUR-THERAIN,milly sur therain,Milly-sur-ThÃ©rain,M426365,MLSR0RN,60112,403,...,86,19.57,2.00000,49.5000,-379,55003,+15943,493009,72,164
690,24029,60,saint-samson-la-poterie,SAINT-SAMSON-LA-POTERIE,saint samson la poterie,Saint-Samson-la-Poterie,S5325254136,SNTSMSNLPTR,60220,596,...,58,4.30,1.74195,49.5939,-660,55105,+14431,493538,145,214
691,24030,60,ver-sur-launette,VER-SUR-LAUNETTE,ver sur launette,Ver-sur-Launette,V626453,FRSRLNT,60950,666,...,90,13.18,2.68333,49.1000,388,54561,+24107,490618,79,116
692,24031,60,moulin-sous-touvent,MOULIN-SOUS-TOUVENT,moulin sous touvent,Moulin-sous-Touvent,M4523153,MLNSSTFNT,60350,438,...,12,18.14,3.07139,49.4564,816,54952,+30417,492723,68,158

In [13]:
# Affichage des 100 première lignes
df_villes_100 = df_villes.head(100)
df_villes_100

,ville_id,ville_departement,ville_slug,ville_nom,ville_nom_simple,ville_nom_reel,ville_nom_soundex,ville_nom_metaphone,ville_code_postal,ville_commune,...,ville_densite_2010,ville_surface,ville_longitude_deg,ville_latitude_deg,ville_longitude_grd,ville_latitude_grd,ville_longitude_dms,ville_latitude_dms,ville_zmin,ville_zmax
0,1,01,ozan,OZAN,ozan,Ozan,O250,OSN,01190,284,...,93,6.60,4.91667,46.3833,2866,51546,+45456,462330,170.0,205.0
1,2,01,cormoranche-sur-saone,CORMORANCHE-SUR-SAONE,cormoranche sur saone,Cormoranche-sur-SaÃ´ne,C65652625,KRMRNXSRSN,01290,123,...,107,9.85,4.83333,46.2333,2772,51379,+44953,461427,168.0,211.0
2,3,01,plagne-01,PLAGNE,plagne,Plagne,P425,PLKN,01130,298,...,20,6.20,5.73333,46.1833,3769,51324,+54342,461131,560.0,922.0
3,4,01,tossiat,TOSSIAT,tossiat,Tossiat,T230,TST,01250,422,...,138,10.17,5.31667,46.1333,3309,51268,+51854,460828,244.0,501.0
4,5,01,pouillat,POUILLAT,pouillat,Pouillat,P430,PLT,01250,309,...,14,6.23,5.43333,46.3333,3435,51475,+52542,461938,333.0,770.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,01,petit-abergement,LE PETIT-ABERGEMENT,le petit abergement,Le Petit-Abergement,L1316253,LPTTBRJMNT,01260,292,...,5,26.95,5.65000,46.0333,3697,51147,+53949,460157,706.0,1177.0
96,97,01,cormoz,CORMOZ,cormoz,Cormoz,C652,KRMS,01560,124,...,31,19.56,5.23333,46.4500,3217,51610,+51356,462657,187.0,223.0
97,98,01,saint-martin-de-bavel,SAINT-MARTIN-DE-BAVEL,saint martin de bavel,Saint-Martin-de-Bavel,S535635314,SNTMRTNTBFL,01510,372,...,52,8.50,5.68333,45.8500,3712,50944,+54039,455057,249.0,442.0
98,99,01,saint-trivier-de-courtes,SAINT-TRIVIER-DE-COURTES,saint trivier de courtes,Saint-Trivier-de-Courtes,S5361632632,SNTTRFRTKRTS,01560,388,...,61,16.53,5.08333,46.4667,3050,51622,+50453,462735,184.0,218.0
99,100,01,boyeux-saint-jerome,BOYEUX-SAINT-JEROME,boyeux saint jerome,Boyeux-Saint-JÃ©rÃ´me,B253265,BYKSSNTJRM,01640,056,...,18,16.94,5.46667,46.0333,3467,51144,+52724,460148,329.0,900.0

In [16]:
from datetime import datetime

def obtenir_date_heure() -> str:
    date_heure_format = "%d/%m/%Y %H:%M:%S"
    now = datetime.now()
    return now.strftime(date_heure_format)

In [17]:
# Sauvegarde dans Excel les 100 premières lignes
fichier_de_sauvegarde = "output_villes.xlsx"
df_villes_100.to_excel(fichier_de_sauvegarde, index=False)
print("Les données ont été sauvegardées dans le fichier", fichier_de_sauvegarde)
print("Date et heure de sauvegarde", obtenir_date_heure())

Les données ont été sauvegardées dans le fichier output_villes.xlsx
Date et heure de sauvegarde 20/09/2024 16:15:24

In [18]:
# Sauvegarde dans une table de base de données
nom_table = "ville_output"
df_villes_departement.to_sql(nom_table, engine, if_exists='replace', index=False)
print("Les données ont été sauvegardées dans la table", nom_table)
print("Date et heure de sauvegarde", obtenir_date_heure())

Les données ont été sauvegardées dans la table ville_output
Date et heure de sauvegarde 20/09/2024 16:15:49